version: '3.8'
services: 
  influxdb:
    image: influxdb:2.4.0-alpine
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=jmeter
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=TEDl_9CsiEv1QCy7c94IK3XijHNCqI0bB29yIYwJGsBOUFD50fI2Dc8gm_bjd5uzeZZU21aSHhPSSbLo8oNPSA==
    ports:
      - 8087:8086
    volumes:
      - $PWD/data:/var/lib/influxdb2
      - $PWD/config:/etc/influxdb2
  jmeter-master:
    image: spirlhark/jmeter_5.5:v1
    volumes:
      - $PWD/company/:/jmeter/company/
    depends_on:
      - influxdb
    env_file:
      - .env
    command: ["sh", "-c", "JVM_ARGS='-Xms1024m -Xmx7000m' jmeter --nongui --testfile company/restful-booker_v5_5.jmx -Dserver.rmi.ssl.disable=true -Jthreads1=2 -Jrampup1=1"]
#    ["sh", "-c", "sleep infinity"]
 grafana:
    image: grafana/grafana:9.1.2
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
    - grafana-storage:/var/lib/grafana

volumes:
  influxdb-storage:
  grafana-storage:
